### PR TITLE
Update ruby patchlevel to match tahi.

### PR DESCRIPTION
**Pull request by mcantor**
To stay in sync with [tahi/pull/1353](https://github.com/Tahi-project/tahi/pull/1353).

### CODE REVIEW

**Comment by mikem** [comment]
:+1:

**Comment by mikem** [comment]
Oh, there are [more references to Ruby](https://github.com/Tahi-project/tahi-slanger/blob/ece0983007da01dee18c76a44dca50a1bd7a89e7/ansible/roles/ruby/tasks/main.yml#L10-L17) in the repo, in `tahi-slanger/ansible/roles/ruby/tasks/main.yml`. It'd be good to know whether those need to be bumped too, somehow. /c @surfacedamage

**Comment by rizwanreza** [comment]
I have messaged @surfacedamage about it, I am going to merge this as I need it.

**Comment by surfacedamage** [comment]
No, they don't need changed.  Servers are running `2.2.2.

**Pull request merged**
